Deploying istio update
OpenLiberty/guide-istio-intro pull request #108
Opened 2020-10-09 22:56 UTC by tt-le

Issue:  @[OpenLiberty/guide-istio-intro](https://github.com/OpenLiberty/guide-istio-intro/issues/106)

Updated deploy istio section to use `istioctl` for installation and update tearing down section with `istioctl`.

2020-10-14 13:29 UTC, AustinSeto requested changes
Just a few changes

2020-10-14 13:29 UTC, AustinSeto commented on README.adoc
> +First, go to the https://github.com/istio/istio/releases/latest[{istio} release page^] and download the latest stable release. Extract the archive and navigate to the directory with the extracted fil
typo "Add istioctl clien" -> "Add the istioctl client"

2020-10-14 13:29 UTC, AustinSeto commented on README.adoc
> +----
I think this needs to go after the `istioctl install --set profile=demo` command, as I don't get this output for `istioctl version` until after I do that command.

2020-10-14 13:29 UTC, AustinSeto commented on README.adoc
> +```
I think this is a duplicate command box, and it still has the comment to run `kubectl apply` even though this was removed

2020-10-14 15:02 UTC, AustinSeto requested changes
Missed these ones earlier, just some small text edits. Other than that, everything else looks good, verified on LGDEV site.

2020-10-14 15:24 UTC, tt-le commented
@AustinSeto I just added the text edits. Thanks

2020-10-14 15:59 UTC, AustinSeto requested changes

2020-10-14 15:59 UTC, AustinSeto commented on README.adoc
> +----
Sorry missed this one too, should add a similar comment saying, "The output will be similar to the following example."

2020-10-14 21:07 UTC, tt-le commented
@AustinSeto I just added the texts. What do you think now?

2020-10-15 13:21 UTC, AustinSeto approved these changes
LGTM

2020-10-21 21:16 UTC, gkwan-ibm requested changes
@tt-le 
- **Deploying Istio**
  - [x] update the first pargaraph and remove the PATH command
- **Deploying version 1 of the system microservice**
  - [ ] "Navigate to the `start` directory ..." -> "Navigate to the `guide-istio-intro\start` directory ..." 
  - [ ] no need to have `cd start`
- **Testing microservices that are running on Kubernetes**
  - [ ] no test be run
    - need to add `mvn test-compile` before `mvn failsafe:integration-test`
    - "Run the command to start the tests:" -> "Run the following commands to compile and start the tests:"

2020-10-22 19:18 UTC, gkwan-ibm commented
@tt-le 
- **Deploying version 1 of the system microservice**
  - change  "Navigate to the `guide-istio-intro\start` directory ..." -> "Navigate to the `guide-{projectid}\start` directory ..."

2020-10-29 20:10 UTC, gkwan-ibm requested changes

2020-10-29 20:10 UTC, gkwan-ibm commented on README.adoc
> +Navigate to the `guide-{projectid}\start` directory and run the following command to build the application locally.
@tt-le change `guide-{projectid}\start` to `guide-{projectid}/start`

2020-11-02 22:09 UTC, tt-le commented
Addressed feedback. Changed the README to use the guides-commons adoc.

2020-11-03 16:41 UTC, Charlotte-Holt approved these changes

2020-11-03 17:22 UTC, gkwan-ibm approved these changes

2020-11-03 17:24 UTC, merged